import FWCore.ParameterSet.Config as cms

process = cms.Process("Demo")

process.load("FWCore.MessageService.MessageLogger_cfi")
process.load('Configuration.Geometry.GeometryExtended2023D20Reco_cff')


process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')

from Configuration.AlCa.GlobalTag import GlobalTag
process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:run2_mc', '')

process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )

process.source = cms.Source("PoolSource",
    # replace 'myfile.root' with the source file you want to use
    fileNames = cms.untracked.vstring(
        #'file:myfile.root'
	#'root://cms-xrd-global.cern.ch//store/mc/PhaseIITDRFall17DR/SingleGammaPt50Eta1p6_2p8/GEN-SIM-RECO/PU200FEVT_93X_upgrade2023_realistic_v2-v1/00000/900213BF-61BE-E711-BB08-B499BAABFEB0.root',
	#'root://cms-xrd-global.cern.ch//store/mc/PhaseIITDRFall17DR/SingleGammaPt50Eta1p6_2p8/GEN-SIM-RECO/PU200FEVT_93X_upgrade2023_realistic_v2-v1/00000/C2E8F82A-5CBE-E711-B96E-0CC47A78A45A.root',
	#'root://cms-xrd-global.cern.ch//store/mc/PhaseIITDRFall17DR/SingleGammaPt50Eta1p6_2p8/GEN-SIM-RECO/PU200FEVT_93X_upgrade2023_realistic_v2-v1/00000/D4512BAD-5EBE-E711-8298-0CC47A4C8F08.root',
	#'root://cms-xrd-global.cern.ch//store/mc/PhaseIITDRFall17DR/SingleGammaPt50Eta1p6_2p8/GEN-SIM-RECO/PU200FEVT_93X_upgrade2023_realistic_v2-v1/00000/E83F2118-6ABE-E711-B3E3-001CC4A6AE4E.root',
	#'root://cms-xrd-global.cern.ch//store/mc/PhaseIITDRFall17DR/SingleGammaPt50Eta1p6_2p8/GEN-SIM-RECO/PU200FEVT_93X_upgrade2023_realistic_v2-v1/010000/2C646B14-99BD-E711-A3FD-001E67792488.root',
	#'root://cms-xrd-global.cern.ch//store/mc/PhaseIITDRFall17DR/SingleGammaPt50Eta1p6_2p8/GEN-SIM-RECO/PU200FEVT_93X_upgrade2023_realistic_v2-v1/010000/C4F7A2B7-97BD-E711-8EEA-0242AC1C0500.root',
	#'root://cms-xrd-global.cern.ch//store/mc/PhaseIITDRFall17DR/SingleGammaPt50Eta1p6_2p8/GEN-SIM-RECO/PU200FEVT_93X_upgrade2023_realistic_v2-v1/010000/CA7666CE-97BD-E711-B06C-0242AC1C0500.root',
	#'root://cms-xrd-global.cern.ch//store/mc/PhaseIITDRFall17DR/SingleGammaPt50Eta1p6_2p8/GEN-SIM-RECO/PU200FEVT_93X_upgrade2023_realistic_v2-v1/150000/060576FB-24B1-E711-8A3A-7CD30AD09DD2.root',
	#'root://cms-xrd-global.cern.ch//store/mc/PhaseIITDRFall17DR/SingleGammaPt50Eta1p6_2p8/GEN-SIM-RECO/PU200FEVT_93X_upgrade2023_realistic_v2-v1/150000/0EDC39CF-73B4-E711-8458-E0071B7A45D0.root',
	#'root://cms-xrd-global.cern.ch//store/mc/PhaseIITDRFall17DR/SingleGammaPt50Eta1p6_2p8/GEN-SIM-RECO/PU200FEVT_93X_upgrade2023_realistic_v2-v1/150000/0EEE9C34-94B4-E711-8E23-5065F381E251.root',
	#'root://cms-xrd-global.cern.ch//store/mc/PhaseIITDRFall17DR/SingleGammaPt50Eta1p6_2p8/GEN-SIM-RECO/PU200FEVT_93X_upgrade2023_realistic_v2-v1/150000/FEC761B6-6BB3-E711-87FF-003048C91B0E.root',),
	#'root://cms-xrd-global.cern.ch//store/user/mressego/ME0trigger/B0ToTau_To3Mu_beamspot14TeV_filterME0_padbased-step3_200evt/180716_110330/0000/step3_beamspot14TeV_1.root'),
	#'root://cms-xrd-global.cern.ch://store/mc/PhaseIITDRSpring17DR/DoubleNuE1Eta14_31/GEN-SIM-RECO/PU200_NoSmear_91X_upgrade2023_realistic_v3-v2/110000/000DC127-7371-E711-9E21-F02FA768CCE6.root'
         'root://cms-xrd-global.cern.ch://store/mc/PhaseIITDRSpring17DR/DoubleNuE1Eta14_31/GEN-SIM-RECO/PU200_NoSmear_91X_upgrade2023_realistic_v3-v2/110000/221DC244-B971-E711-8285-3417EBE643E7.root'),
#    dropDescendantsOfDroppedBranches=cms.untracked.bool(False),
#    inputCommands = cms.untracked.vstring( 'drop *',
#    'keep *_simMuonGEMDigis_GEM_HLT',     
#    'keep *_csc2DRecHits_*_RECO',    
#    'keep *_cscSegments_*_RECO',    
#    'keep *_dt4DCosmicSegments_*_RECO',    
#    'keep *_dt4DSegments_*_RECO',    
#    'keep *_dt1DCosmicRecHits_*_RECO',    
#    'keep *_dt1DRecHits_*_RECO',    
#    'keep *_gemRecHits_*_RECO',    
#    'keep *_gemSegments_*_RECO',    
#    'keep *_me0RecHits_*_RECO',    
#    'keep *_me0Segments_*_RECO',    
#    'keep *_rpcRecHits_*_RECO',    
#    'keep *_simMuonCSCDigis_MuonCSCStripDigiSimLinks_HLT',     
#    'keep *_simMuonCSCDigis_MuonCSCWireDigiSimLinks_HLT',     
#    'keep *_csc2DRecHits_*_RECO',    
#    'keep *_cscSegments_*_RECO',    
#    'keep *_muons_csc_RECO',    
#    'keep *_CSCHaloData_*_RECO',    
#    'keep *_simMuonME0Digis_ME0_HLT',     
#    'keep *_me0RecHits_*_RECO',    
#    'keep *_me0Segments_*_RECO',    
#    'keep *_me0SegmentMatching_*_RECO',    
#    'keep *_me0MuonConverting_*_RECO',    
#    'keep *_g4SimHits_*_SIM',     
#    'keep *_simMuonDTDigis_*_HLT',     
#    'keep *_simMuonRPCDigis_RPCDigiSimLink_HLT',     
#    'keep *_simMuonGEMDigis_GEM_HLT',     
#    'keep *_simMuonME0Digis_ME0_HLT',     
#    'keep *_simMuonCSCDigis_MuonCSCStripDigiSimLinks_HLT',     
#    'keep *_simMuonCSCDigis_MuonCSCWireDigiSimLinks_HLT',     
#    'keep *_gmtStage2Digis_Muon_RECO',    
#    'keep *_gtStage2Digis_Muon_RECO',    
#    'keep *_gmtStage2Digis_MuonCopy1_RECO',    
#    'keep *_gmtStage2Digis_MuonCopy2_RECO',    
#    'keep *_gmtStage2Digis_MuonCopy3_RECO',    
#    'keep *_gmtStage2Digis_MuonCopy4_RECO',    
#    'keep *_gmtStage2Digis_MuonCopy5_RECO',    
#    'keep *_gmtStage2Digis_imdMuonsBMTF_RECO',    
#    'keep *_gmtStage2Digis_imdMuonsEMTFNeg_RECO',    
#    'keep *_gmtStage2Digis_imdMuonsEMTFPos_RECO',    
#    'keep *_gmtStage2Digis_imdMuonsOMTFNeg_RECO',    
#    'keep *_gmtStage2Digis_imdMuonsOMTFPos_RECO',    
#    'keep *_gmtStage2Digis_BMTF_RECO',    
#    'keep *_gmtStage2Digis_EMTF_RECO',    
#    'keep *_gmtStage2Digis_OMTF_RECO',    
#    'keep *_gtDigis_*_RECO',    
#    'keep *_tevMuons_default_RECO',    
#    'keep *_tevMuons_dyt_RECO',    
#    'keep *_tevMuons_firstHit_RECO',    
#    'keep *_tevMuons_picky_RECO',    
#    'keep *_softPFMuonBJetTags_*_RECO',    
#    'keep *_cosmicMuons_*_RECO',    
#    'keep *_cosmicMuons1Leg_*_RECO',    
#    'keep *_displacedGlobalMuons_*_RECO',    
#    'keep *_displacedStandAloneMuons_*_RECO',    
#    'keep *_electronGsfTracksFromMultiCl_*_RECO',    
#    'keep *_globalMuons_*_RECO',    
#    'keep *_refittedStandAloneMuons_*_RECO',    
#    'keep *_standAloneMuons_*_RECO',    
#    'keep *_tevMuons_default_RECO',    
#    'keep *_tevMuons_dyt_RECO',    
#    'keep *_tevMuons_firstHit_RECO',    
#    'keep *_tevMuons_picky_RECO',    
#    'keep *_muons_muidAllArbitrated_RECO',    
#    'keep *_muons_muidGMStaChiCompatibility_RECO',    
#    'keep *_muons_muidGMTkChiCompatibility_RECO',    
#    'keep *_muons_muidGMTkKinkTight_RECO',    
#    'keep *_muons_muidGlobalMuonPromptTight_RECO',    
#    'keep *_muons_muidRPCMuLoose_RECO',    
#    'keep *_muons_muidTM2DCompatibilityLoose_RECO',    
#    'keep *_muons_muidTM2DCompatibilityTight_RECO',    
#    'keep *_muons_muidTMLastStationAngLoose_RECO',    
#    'keep *_muons_muidTMLastStationAngTight_RECO',    
#    'keep *_muons_muidTMLastStationLoose_RECO',    
#    'keep *_muons_muidTMLastStationOptimizedLowPtLoose_RECO',    
#    'keep *_muons_muidTMLastStationOptimizedLowPtTight_RECO',    
#    'keep *_muons_muidTMLastStationTight_RECO',    
#    'keep *_muons_muidTMOneStationAngLoose_RECO',    
#    'keep *_muons_muidTMOneStationAngTight_RECO',    
#    'keep *_muons_muidTMOneStationLoose_RECO',    
#    'keep *_muons_muidTMOneStationTight_RECO',    
#    'keep *_muons_muidTrackerMuonArbitrated_RECO',    
#    'keep *_muons_muPFMeanDRIsoValueCharged03_RECO',    
#    'keep *_muons_muPFMeanDRIsoValueCharged04_RECO',    
#    'keep *_muons_muPFMeanDRIsoValueChargedAll03_RECO',    
#    'keep *_muons_muPFMeanDRIsoValueChargedAll04_RECO',    
#    'keep *_muons_muPFMeanDRIsoValueGamma03_RECO',    
#    'keep *_muons_muPFMeanDRIsoValueGamma04_RECO',    
#    'keep *_muons_muPFMeanDRIsoValueGammaHighThreshold03_RECO',    
#    'keep *_muons_muPFMeanDRIsoValueGammaHighThreshold04_RECO',    
#    'keep *_muons_muPFMeanDRIsoValueNeutral03_RECO',    
#    'keep *_muons_muPFMeanDRIsoValueNeutral04_RECO',    
#    'keep *_muons_muPFMeanDRIsoValueNeutralHighThreshold03_RECO',    
#    'keep *_muons_muPFMeanDRIsoValueNeutralHighThreshold04_RECO',    
#    'keep *_muons_muPFMeanDRIsoValuePU03_RECO',    
#    'keep *_muons_muPFMeanDRIsoValuePU04_RECO',    
#    'keep *_muons_muPFSumDRIsoValueCharged03_RECO',    
#    'keep *_muons_muPFSumDRIsoValueCharged04_RECO',    
#    'keep *_muons_muPFSumDRIsoValueChargedAll03_RECO',    
#    'keep *_muons_muPFSumDRIsoValueChargedAll04_RECO',    
#    'keep *_muons_muPFSumDRIsoValueGamma03_RECO',    
#    'keep *_muons_muPFSumDRIsoValueGamma04_RECO',    
#    'keep *_muons_muPFSumDRIsoValueGammaHighThreshold03_RECO',    
#    'keep *_muons_muPFSumDRIsoValueGammaHighThreshold04_RECO',    
#    'keep *_muons_muPFSumDRIsoValueNeutral03_RECO',    
#    'keep *_muons_muPFSumDRIsoValueNeutral04_RECO',    
#    'keep *_muons_muPFSumDRIsoValueNeutralHighThreshold03_RECO',    
#    'keep *_muons_muPFSumDRIsoValueNeutralHighThreshold04_RECO',    
#    'keep *_muons_muPFSumDRIsoValuePU03_RECO',    
#    'keep *_muons_muPFSumDRIsoValuePU04_RECO',    
#    'keep *_particleFlowSuperClusterHGCalFromMultiCl_PFClusterAssociationEBEE_RECO',    
#    'keep *_particleFlowSuperClusterHGCalFromMultiCl_PFClusterAssociationES_RECO',    
#    'keep *_particleFlow_muons_RECO',    
#    'keep *_muIsoDepositJets_*_RECO',    
#    'keep *_muIsoDepositTk_*_RECO',    
#    'keep *_muIsoDepositCalByAssociatorTowers_ecal_RECO',    
#    'keep *_muIsoDepositCalByAssociatorTowers_hcal_RECO',    
#    'keep *_muIsoDepositCalByAssociatorTowers_ho_RECO',    
#    'keep *_muons_cosmicsVeto_RECO',    
#    'keep *_muonMETValueMapProducer_muCorrData_RECO',    
#    'keep *_muons_muonShowerInformation_RECO',    
#    'keep *_muons_combined_RECO',    
#    'keep *_muons_csc_RECO',    
#    'keep *_muons_dt_RECO',    
#    'keep *_muons_cosmicsVeto_RECO',    
#    'keep *_hpsPFTauDiscriminationByLooseMuonRejection3_*_RECO',    
#    'keep *_hpsPFTauDiscriminationByTightMuonRejection3_*_RECO',    
#    'keep *_CosmicMuonSeed_*_RECO',    
#    'keep *_ancientMuonSeed_*_RECO',    
#    'keep *_displacedMuonSeeds_*_RECO',    
#    'keep *_l1extraParticles_*_RECO',    
#    'keep *_particleFlowSuperClusterHGCalFromMultiCl_*_RECO',    
#    'keep *_multi5x5SuperClusters_multi5x5EndcapBasicClusters_RECO',    
#    'keep *_particleFlowSuperClusterHGCalFromMultiCl_particleFlowBasicClusterECALBarrel_RECO',    
#    'keep *_particleFlowSuperClusterHGCalFromMultiCl_particleFlowBasicClusterECALPreshower_RECO',    
#    'keep *_multi5x5SuperClusters_uncleanOnlyMulti5x5EndcapBasicClusters_RECO',    
#    'keep *_electronMergedSeedsFromMultiCl_*_RECO',    
#    'keep *_ecalDrivenGsfElectronsFromMultiCl_*_RECO',    
#    'keep *_ecalDrivenGsfElectronCoresFromMultiCl_*_RECO',    
#    'keep *_electronGsfTracksFromMultiCl_*_RECO',    
#    'keep *_electronGsfTracksFromMultiCl_*_RECO',    
#    'keep *_hgcalLayerClusters_*_RECO',    
#    'keep *_hgcalLayerClusters_sharing_RECO',    
#    'keep *_me0SegmentMatching_*_RECO',    
#    'keep *_muons_*_RECO',    
#    'keep *_muonsFromCosmics_*_RECO',    
#    'keep *_muonsFromCosmics1Leg_*_RECO',    
#    'keep *_particleFlowClusterHGCalFromMultiCl_*_RECO',    
#    'keep *_photonsFromMultiCl_*_RECO',    
#    'keep *_photonCoreFromMultiCl_*_RECO',    
#    'keep *_multi5x5SuperClustersWithPreshower_preshowerXClusters_RECO',    
#    'keep *_multi5x5SuperClustersWithPreshower_preshowerYClusters_RECO',    
#    'keep *_multi5x5PreshowerClusterShape_multi5x5PreshowerXClustersShape_RECO',    
#    'keep *_multi5x5PreshowerClusterShape_multi5x5PreshowerYClustersShape_RECO',    
#    'keep *_me0MuonConverting_*_RECO',    
#    'keep *_correctedMulti5x5SuperClustersWithPreshower_*_RECO',    
#    'keep *_multi5x5SuperClustersWithPreshower_*_RECO',    
#    'keep *_particleFlowSuperClusterHGCalFromMultiCl_*_RECO',    
#    'keep *_multi5x5SuperClusters_multi5x5EndcapSuperClusters_RECO',    
#    'keep *_particleFlowSuperClusterHGCalFromMultiCl_particleFlowSuperClusterECALBarrel_RECO',    
#    'keep *_multi5x5SuperClusters_uncleanOnlyMulti5x5EndcapSuperClusters_RECO',    
#    'keep *_softPFMuonsTagInfos_*_RECO',    
#    'keep *_cosmicMuons_*_RECO',    
#    'keep *_cosmicMuons1Leg_*_RECO',    
#    'keep *_displacedGlobalMuons_*_RECO',    
#    'keep *_displacedStandAloneMuons_*_RECO',    
#    'keep *_globalMuons_*_RECO',    
#    'keep *_refittedStandAloneMuons_*_RECO',    
#    'keep *_standAloneMuons_*_RECO',    
#    'keep *_refittedStandAloneMuons_UpdatedAtVtx_RECO',    
#    'keep *_standAloneMuons_UpdatedAtVtx_RECO',    
#    'keep *_tevMuons_default_RECO',    
#    'keep *_tevMuons_dyt_RECO',    
#    'keep *_tevMuons_firstHit_RECO',    
#    'keep *_tevMuons_picky_RECO',    
#    'keep *_cosmicMuons_*_RECO',    
#    'keep *_cosmicMuons1Leg_*_RECO',    
#    'keep *_displacedGlobalMuons_*_RECO',    
#    'keep *_displacedStandAloneMuons_*_RECO',    
#    'keep *_electronGsfTracksFromMultiCl_*_RECO',    
#    'keep *_globalMuons_*_RECO',    
#    'keep *_refittedStandAloneMuons_*_RECO',    
#    'keep *_standAloneMuons_*_RECO',    
#    'keep *_tevMuons_default_RECO',    
#    'keep *_tevMuons_dyt_RECO',    
#    'keep *_tevMuons_firstHit_RECO',    
#    'keep *_tevMuons_picky_RECO',    
#    'keep *_TriggerResults_*_SIM',     
#    'keep *_TriggerResults_*_HLT',     
#    'keep *_hltTriggerSummaryAOD_*_HLT',     
#    'keep *_ecalCompactTrigPrim_*_RECO',    
#    'keep *_gtDigis_*_RECO',    
#    'keep *_ecalTPSkim_*_RECO',    
#    'keep *_TriggerResults_*_RECO',    
#    'keep *_tcdsDigis_triggerCount_RECO',    
#    'keep *_scalersRawToDigi_*_RECO',    
#    'keep *_scalersRawToDigi_*_RECO',    
#    'keep *_generator_*_SIM',     
#    'keep *_generatorSmeared_*_SIM',     
#    'keep *_TriggerResults_*_SIM',     
#    'keep *_g4SimHits_*_SIM',     
#    'keep *_g4SimHits_*_SIM',     
#    'keep *_simMuonDTDigis_*_HLT',     
#    'keep *_simMuonRPCDigis_RPCDigiSimLink_HLT',     
#    'keep *_simMuonGEMDigis_GEM_HLT',     
#    'keep *_simMuonME0Digis_ME0_HLT',     
#    'keep *_simMuonCSCDigis_MuonCSCStripDigiSimLinks_HLT',     
#    'keep *_simMuonCSCDigis_MuonCSCWireDigiSimLinks_HLT',     
#    'keep *_mix_MergedCaloTruth_HLT',     
#    'keep *_pfSimpleInclusiveSecondaryVertexHighEffBJetTags_*_RECO',    
#    'keep *_pfSimpleSecondaryVertexHighEffBJetTags_*_RECO',    
#    'keep *_simPFProducer_*_RECO',    
#    'keep *_simPFProducer_perfect_RECO',    
#    'keep *_simMuonRPCDigis_RPCDigiSimLink_HLT',     
#    'keep *_rpcRecHits_*_RECO',    
#    'keep *_muons_muidRPCMuLoose_RECO') 
)


process.demo = cms.EDAnalyzer('DeltaGlobalPhiAnalyzerMinbias',
    me0Segments = cms.InputTag("me0Segments","","RECO"),
    cscSegments = cms.InputTag("cscSegments","","RECO"),
    gemSegments = cms.InputTag("gemSegments","","RECO"),
    l1tSegments = cms.InputTag("simEmtfDigis", "EMTF", "HLT"),
    genParticles = cms.InputTag("genParticles"),
    verbose = cms.bool(True),
    reco = cms.bool(True), #True if DIGI, False if PAD based
    mutype = cms.bool(True), #True to use thresholds for PROMPT muons , False to use thresholds for DISPLACED muons
    signal = cms.bool(False) #True if running on dataset with simulated signal, False if running on minBias dataset
)

process.TFileService = cms.Service("TFileService",
    fileName = cms.string('out_DeltaGlobalPhiAnalyzerMinbias.root'))

process.p = cms.Path(process.demo)
